### ISSUE TITLE
GetTypeForLevel sometimes returns incorrect BidiClass

### ISSUE THREAD

**Issue by elyoh** [fsufyan/BidiSharp#1]
https://github.com/fsufyan/BidiSharp/blob/f090ab32c1951e2c4d9329601eee07690a6bb7b1/BidiSharp/Source/Bidi.cs#L865-L869

The method should return BidiClass.L when level is even and BidiClass.R when level is odd.

However `(level & 2) == 0` is not true for all even levels and false for all odd levels e.g.
`(2 & 2) == 0` is `false`
`(8 & 2) == 0` is `true`
`(9 & 2) == 0` is `true`

Consequently `LogicalToVisual `returns incorrect values in some cases.

Method should use `(level & 1) == 0`.

**Comment by fsufyan** [comment]
The issue has been fixed in f69903f93f0ca4c06e88f9fa9d74a13074cebb27
Thank you.
