### ISSUE TITLE
Reshaping of characters is not implemented

### ISSUE THREAD

**Issue by hk1ll3r** [fsufyan/BidiSharp#2]
For languages like Persian and Arabic the characters take different shapes depending on their position in each word. This is part of the ICU unicode algorithm explained here:
http://www.unicode.org/reports/tr9/#Reordering_Resolved_Levels

Any chance this could be added to the library?

**Comment by fsufyan** [comment]
Unfortunately, this is a complete different scope from what this tool does.
What you are seeking is called Text Shaping, checkout this C library **HarfBuzz** it does the text shaping.

More info on this link https://harfbuzz.github.io/what-harfbuzz-doesnt-do.html.

**Comment by hk1ll3r** [comment]
> Unfortunately, this is a complete different scope from what this tool does. What you are seeking is called Text Shaping, checkout this C library **HarfBuzz** it does the text shaping.
> 
> More info on this link https://harfbuzz.github.io/what-harfbuzz-doesnt-do.html.

Thanks for the reply @fsufyan . I understand the difference. Unfortunately I haven't been able to find harfbuzz for CSharp but I know its out there (called harfbuzzsharp). I'll keep looking :)
